source: site
paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: collections
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: collections/_pages
    output: true
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/page.html
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  projects:
    path: collections/_projects
    output: true
    description: ''
    icon: work_outline
    preview:
      text:
      subtext:
        - key: subtitle
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/project.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
  - heading: Settings
    collections:
      - data
_inputs:
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_structures:
  content_blocks:
    style: modal
data_config: true
timezone: America/La_Paz
